### ISSUE TITLE
Include detail from header tooltips in module reference

### ISSUE THREAD

**Issue by elstoc** [elstoc/dtdocs#132]
Processing module headers in darktable now contain a brief summary of the module along with details of the purpose, input, output and working color spaces. 

Consider including this in the dtdocs module reference sections. Some of it is already included but not yet visible.

Should we use the yaml metadata to include this detail or include it as separate content?

**Comment by paperdigits** [comment]
Can you provide some samples of what these tooltips look like?

**Comment by elstoc** [comment]
![Screenshot_2020-11-19_07-52-39](https://user-images.githubusercontent.com/9555491/99637105-47722780-2a3c-11eb-95e9-e9b67aa43791.png)

**Comment by raublekick** [comment]
If there's still interest in this I'm happy to grind through the modules. I did a little proof of concept. For my own possible future reference: It's "easy" to find the info in the darktable codebase searching for instances of `dt_iop_set_description`.  You can use the `name` function to see the name of the module to match it to a .md file in the docs:

```c
const char *name()
{
  return _("AgX");
}

const char **description(dt_iop_module_t *self)
{
  return dt_iop_set_description(self,
                                _("applies a tone mapping curve.\n"
                                    "inspired by Blender's AgX tone mapper"),
                                _("corrective and creative"),
                                _("linear, RGB, scene-referred"),
                                _("non-linear, RGB"),
                                _("linear, RGB, display-referred"));
}
```
Added to the AgX yaml:
```yaml
---
title: AgX
id: agx
weight: 10
params:
    module_info:
        description: "applies a tone mapping curve. inspired by Blender's AgX tone mapper"
        purpose: "corrective and creative"
        input: "linear, RGB, scene-referred"
        processing: "non-linear, RGB"
        output: "linear, RGB, display-referred"
---
```

Rendered:

<img width="1134" height="561" alt="Image" src="https://github.com/user-attachments/assets/38b74086-66b6-4cd8-89f3-97d5b10ab688" />

I had to edit the theme template but I didn't bother trying to style it any particular way.
